{% set name = "littleutils" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c7835b01020ced42e291118b7d78fb16bc2d9a1b4f3f42f3cb3787bb4da53d19

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - littleutils

about:
  home: https://github.com/alexmojaki/littleutils
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Small personal collection of python utility functions, partly just for fun'

extra:
  recipe-maintainers:
    - hoechenberger
